# meta developer: @RemoveWoman

from .. import loader
from asyncio import sleep


@loader.tds
class HitlerZigMod(loader.Module):
    strings = {"name": "hitler"}

    @loader.owner
    async def facepalmcmd(self, message):
        for _ in range(10):
            for facepalm in [" 🤷 ", " 🤦 "]:
                await message.edit(facepalm)
                await sleep(0.6)


    async def upacmd(self, message):
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟦🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟦🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟦🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟦🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟦🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟦🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟦🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟦🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟦🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟦🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟦🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟦🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟦\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟦\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟦\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟦\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟦")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟦🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟦🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟦🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟦🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟦🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟦🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟨🟨🟨🟨🟨\n🟦🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟦🟨🟦🟨🟦\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟦🟨🟦🟨🟦\n🟨🟦🟨🟦🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟦🟨🟦🟨🟦\n🟨🟦🟨🟦🟨\n🟦🟨🟦🟨🟦\n🟨🟨🟨🟨🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟦🟨🟦🟨🟦\n🟨🟦🟨🟦🟨\n🟦🟨🟦🟨🟦\n🟨🟦🟨🟦🟨\n🟨🟨🟨🟨🟨")
    	await sleep(0.2)
    	await message.edit("🟦🟨🟦🟨🟦\n🟨🟦🟨🟦🟨\n🟦🟨🟦🟨🟦\n🟨🟦🟨🟦🟨\n🟦🟨🟦🟨🟦")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥\n🟨🟦🟨🟦🟨\n🟦🟨🟦🟨🟦\n🟨🟦🟨🟦🟨\n🟦🟨🟦🟨🟦")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n🟦🟨🟦🟨🟦\n🟨🟦🟨🟦🟨\n🟦🟨🟦🟨🟦")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n🟨🟦🟨🟦🟨\n🟦🟨🟦🟨🟦")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n⬛⬛️️⬛️⬛️️⬛️\n🟦🟨🟦🟨🟦")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n⬛️⬛️⬛️⬛️⬛️\n⬛️⬛️⬛️⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n🟥🟥🟥🟥🟥\n⬛️⬛️⬛️⬛️⬛️\n⬛️⬛️⬛️⬛️⬛️\n⬛️⬛️⬛️⬛️⬛️")
    	
    async def hideevilcmd(self, message):
    	for _ in range(4):
    		for hideevil in ["😇", "👹"]:
    			await message.edit(hideevil)
    			await sleep(0.3)
    			
    async def pigcmd(self, message):
    	for _ in range(4):
    		for pig in ["🐷", "🐽"]:
    			await message.edit(pig)
    			await sleep(0.3)
    async def zig1cmd(self, message):
    			for _ in range(20):
    				await message.edit("⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬜️⬜️⬛️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬛️⬜️⬜️⬜️⬛️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬜️⬛️⬛️\n⬛️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬛️\n⬛️⬛️⬜️⬜️⬛️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬛️⬛️⬛️\n⬛️⬜️⬜️⬜️⬜️\n⬛️⬜️⬜️⬜️⬛️\n⬜️⬜️⬜️⬜️⬛️\n⬛️⬛️⬛️⬜️⬛️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬛️⬛️⬛️\n⬛️⬜️⬛️⬜️⬜️\n⬛️⬛️<emoji document_id=5235987238914892442>🇺🇦</emoji>⬛️⬛️\n⬜️⬜️⬛️⬜️⬛️\n⬛️⬛️⬛️⬜️⬛️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬛️⬛️⬛️\n⬛️⬜️⬛️⬜️⬜️\n⬛️⬛️⬛️⬛️⬛️\n⬜️⬜️⬛️⬜️⬛️\n⬛️⬛️⬛️⬜️⬛️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬛️⬛️⬛️\n⬛️⬜️⬛️⬜️⬜️\n⬛️⬛️⬜️⬛️⬛️\n⬜️⬜️⬛️⬜️⬛️\n⬛️⬛️⬛️⬜️⬛️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬛️⬛️⬛️\n⬛️⬜️⬜️⬜️⬜️\n⬛️⬜️⬜️⬜️⬛️\n⬜️⬜️⬜️⬜️⬛️\n⬛️⬛️⬛️⬜️⬛️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬜️⬛️⬛️\n⬛️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬛️\n⬛️⬛️⬜️⬜️⬛️")
    				await sleep(0.2)
    				await message.edit("⬛️⬜️⬜️⬜️⬛️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬜️⬜️⬜️⬜️⬜️\n⬛️⬜️⬜️⬜️⬛️")
    				await sleep(0.2)
    			await message.edit("⬛️⬜️⬛️⬛️⬛️\n⬛️⬜️⬛️⬜️⬜️\n⬛️⬛️<emoji document_id=5235987238914892442>🇺🇦</emoji>⬛️⬛️\n⬜️⬜️⬛️⬜️⬛️\n⬛️⬛️⬛️⬜️⬛️")
    			
    async def zig2cmd(self, message):
    	await message.edit("🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️🟥\n🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️🟥\n🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️🟥\n🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️🟥\n🟥🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️🟥\n🟥🟥🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️🟥\n🟥🟥🟥🟥🟥🟥")
    	await sleep(0.2)
    	await message.edit("🟥🟥🟥🟥🟥🟥🟥\n🟥⬛️⬜️⬛️⬛️⬛️🟥\n🟥⬛️⬜️⬛️⬜️⬜️🟥\n🟥⬛️⬛️⬛️⬛️⬛️🟥\n🟥⬜️⬜️⬛️⬜️⬛️🟥\n🟥⬛️⬛️⬛️⬜️⬛️🟥\n🟥🟥🟥🟥🟥🟥🟥")
    	
